name = "pokeflip-admin"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "pokeflip-admin"

[env.preview]
name = "pokeflip-admin-preview"

[build]
command = "TURBOPACK=0 npm run build"
